// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6eV8K3u4IMn5lbII9xfRPDMQIeV2XHVc',
    appId: '1:365994525327:web:07ba8985a7628d463ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    authDomain: 'iti-cors.firebaseapp.com',
    storageBucket: 'iti-cors.appspot.com',
    measurementId: 'G-EMWY6N7N1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4wT9ImvJA3HXcnVGNMTEiRwxVMH0Gws',
    appId: '1:365994525327:android:14f188f7aa56a3413ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    storageBucket: 'iti-cors.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1-NIIad-NigTsYUvUq0u30UVXqx21db0',
    appId: '1:365994525327:ios:992dfadd14becdbf3ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    storageBucket: 'iti-cors.appspot.com',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1-NIIad-NigTsYUvUq0u30UVXqx21db0',
    appId: '1:365994525327:ios:992dfadd14becdbf3ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    storageBucket: 'iti-cors.appspot.com',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6eV8K3u4IMn5lbII9xfRPDMQIeV2XHVc',
    appId: '1:365994525327:web:a5cb37075f2eb14e3ca6fa',
    messagingSenderId: '365994525327',
    projectId: 'iti-cors',
    authDomain: 'iti-cors.firebaseapp.com',
    storageBucket: 'iti-cors.appspot.com',
    measurementId: 'G-2STLX0Q4XM',
  );
}
